### ISSUE TITLE
save quizz / list of quizz / add photo

### ISSUE THREAD

**Issue by x0rzkov** [ChrisLubin/Kahoot-Like-App#4]
Hi,

Hope you are all well !

It would be awesome to store quizzes and have a list of them.

Ultimately, it would be nice to add a picture for each questions so this repository would be definitely great :-)

Do you think that we can work together for making it ?

Ps. I made a pull request with a dockerized version of your repo.

Cheers,
X

**Comment by ChrisLubin** [comment]
Hello,

Sorry, but unfortunately I won't be making any meaningful updates to this application. I've considered it "done."
